name: Create Release

on:
  push:
    branches:
      - stable

jobs:
  run-on-main-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: paulhatch/semantic-version@v6.0.2
        